/* ==========================================================================
   Japan Foodmap 4.0.0 — src/tabelog/ui/js/core.js
   The application core: state tree, event bus, render scheduler, back-stack
   router (NAV-03), geometry (LAY-01..05 / ENV-02), i18n, emoji, motion,
   utilities and boot. Classic script; exposes window.App, window.I18N,
   window.t. Owner: architect. Modules never edit this file — file a
   coreRequest in your result instead.

   Ported from ui-captures-2026-09-10/redesign/demo-4.0/js/core.js. What
   changed for production (everything else is the demo, verbatim):
     · t(key) falls back to Business.localizeText(key) — the run-based
       TEXT_*_MAP the build injects — so business-layer status strings and
       any key the UI table lacks still render in the active language.
     · the UI table itself arrives as window.UI_I18N_TABLES (map.py injects
       ui/i18n/ui-strings.json, with zh-TW generated by to_trad()).
     · emoji PNGs resolve through Business.emojiSrc(): docs/emoji/<hex>.png
       when the build's manifest has the glyph, emojicdn otherwise. Never a
       text fallback.
     · App.boot({leafletMap, mapEl}) adopts folium's Leaflet map instead of
       creating one, and no longer knows about scenes or the review deck.
     · state gains `account` and `sync` (mirrored from Business by the
       adapter); `signedIn` stays as a boolean shortcut for the modules.
   ========================================================================== */
(function () {
  'use strict';

  var App = {};
  App.VERSION = '4.0.0';
  App.ready = false;
  App.modules = {};          // name → module object (init/render/destroy)
  App._moduleOrder = [];
  window.App = App;

  /* ========================================================================
     util
     ==================================================================== */
  var util = App.util = {};

  util.clamp = function (v, lo, hi) { return Math.max(lo, Math.min(hi, v)); };

  util.isPlainObject = function (v) {
    return v !== null && typeof v === 'object' && !Array.isArray(v) &&
      !(v instanceof Set) && !(v instanceof Map) && !(v instanceof Element) &&
      Object.getPrototypeOf(v) === Object.prototype;
  };

  util.esc = function (s) {
    if (s === null || s === undefined) return '';
    return String(s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  };

  util.debounce = function (fn, ms) {
    var tm = null;
    var d = function () {
      var self = this, args = arguments;
      clearTimeout(tm);
      tm = setTimeout(function () { tm = null; fn.apply(self, args); }, ms);
    };
    d.cancel = function () { clearTimeout(tm); tm = null; };
    return d;
  };

  var _uid = 0;
  util.uid = function (prefix) {
    _uid += 1;
    return (prefix || 'id') + '-' + Date.now().toString(36) + _uid.toString(36);
  };

  /** on(el, ev, fn, opts) → off() */
  util.on = function (el, ev, fn, opts) {
    if (!el) return function () {};
    el.addEventListener(ev, fn, opts || false);
    return function () { el.removeEventListener(ev, fn, opts || false); };
  };

  /** delegate(root, ev, selector, fn) — fn(e, matchedEl) */
  util.delegate = function (root, ev, selector, fn, opts) {
    return util.on(root, ev, function (e) {
      var el = e.target && e.target.closest ? e.target.closest(selector) : null;
      if (el && root.contains(el)) fn(e, el);
    }, opts);
  };

  /** h('div.cls#id', {attr, on:{click}}, children...) → Element */
  util.h = function (tag, attrs) {
    var m = /^([a-z0-9-]+)?((?:[.#][\w-]+)*)$/i.exec(tag) || [];
    var el = document.createElement(m[1] || 'div');
    (m[2] || '').replace(/([.#])([\w-]+)/g, function (_, k, v) {
      if (k === '.') el.classList.add(v); else el.id = v;
      return '';
    });
    var children = Array.prototype.slice.call(arguments, 2);
    if (attrs && (typeof attrs !== 'object' || attrs instanceof Node || Array.isArray(attrs))) {
      children.unshift(attrs); attrs = null;
    }
    if (attrs) {
      Object.keys(attrs).forEach(function (k) {
        var v = attrs[k];
        if (v === null || v === undefined || v === false) return;
        if (k === 'on' && typeof v === 'object') {
          Object.keys(v).forEach(function (ev) { el.addEventListener(ev, v[ev]); });
        } else if (k === 'html') { el.innerHTML = v; }
        else if (k === 'text') { el.textContent = v; }
        else if (k === 'style' && typeof v === 'object') { Object.assign(el.style, v); }
        else if (k === 'dataset' && typeof v === 'object') { Object.keys(v).forEach(function (d) { el.dataset[d] = v[d]; }); }
        else if (k === 'class' || k === 'className') { el.className += (el.className ? ' ' : '') + v; }
        else if (v === true) { el.setAttribute(k, ''); }
        else { el.setAttribute(k, v); }
      });
    }
    children.forEach(function appendChild(c) {
      if (c === null || c === undefined || c === false) return;
      if (Array.isArray(c)) { c.forEach(appendChild); return; }
      el.appendChild(c instanceof Node ? c : document.createTextNode(String(c)));
    });
    return el;
  };

  util.setWith = function (set, v) { var s = new Set(set); s.add(v); return s; };
  util.setWithout = function (set, v) { var s = new Set(set); s.delete(v); return s; };
  util.setToggle = function (set, v) { return set.has(v) ? util.setWithout(set, v) : util.setWith(set, v); };
  util.setEq = function (a, b) {
    if (a === b) return true;
    if (!a || !b || a.size !== b.size) return false;
    var eq = true; a.forEach(function (v) { if (!b.has(v)) eq = false; });
    return eq;
  };

  util.langLocale = function (lang) {
    return { zh: 'zh-CN', tw: 'zh-TW', en: 'en', ja: 'ja' }[lang] || 'zh-CN';
  };

  /** fmtCount(n) — grouped integer in the UI locale; never a fake "8.1k". */
  util.fmtCount = function (n, lang) {
    n = Number(n) || 0;
    try { return n.toLocaleString(util.langLocale(lang || (App.state && App.state.lang))); }
    catch (e) { return String(n); }
  };

  /** fmtRating(r) — source precision, no padding; null → '' (caller shows a missing state). */
  util.fmtRating = function (r) {
    if (r === null || r === undefined || isNaN(r)) return '';
    var s = String(Math.round(Number(r) * 100) / 100);
    return s;
  };

  /**
   * fmtPrice(bucketKey, {short}) — short map label ('¥20k+') or long
   * filter/detail label ('¥20,000+'); 'na' and unknown → the localized
   * "未知" word. Uses Data.config.PRICE_BUCKETS; never invents ranges.
   */
  util.fmtPrice = function (bucket, opts) {
    var D = window.Data;
    var b = D && D.config && D.config.PRICE_BY_KEY ? D.config.PRICE_BY_KEY[bucket] : null;
    if (!b || bucket === 'na') return window.t('未知');
    return (opts && opts.short) ? b.short : b.label;
  };

  /** fmtYen(n) — actual upper-bound yen from popups (e.g. 49999 → '¥49,999'). */
  util.fmtYen = function (n) {
    if (n === null || n === undefined || n === '' || isNaN(Number(n))) return window.t('未知');
    return '¥' + Number(n).toLocaleString('en-US');
  };

  util.fmtDistance = function (m) {
    if (m === null || m === undefined || isNaN(m)) return '';
    m = Number(m);
    return m < 1000 ? Math.round(m) + ' m' : (Math.round(m / 100) / 10) + ' km';
  };

  util.haversine = function (lat1, lon1, lat2, lon2) {
    var R = 6371000, toR = Math.PI / 180;
    var dLat = (lat2 - lat1) * toR, dLon = (lon2 - lon1) * toR;
    var a = Math.sin(dLat / 2) * Math.sin(dLat / 2) +
      Math.cos(lat1 * toR) * Math.cos(lat2 * toR) * Math.sin(dLon / 2) * Math.sin(dLon / 2);
    return 2 * R * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  };

  util.rectsIntersect = function (a, b) {
    return a.x < b.x + b.w && a.x + a.w > b.x && a.y < b.y + b.h && a.y + a.h > b.y;
  };

  util.raf = function (fn) { return window.requestAnimationFrame(fn); };

  /* ========================================================================
     icons — one stroke style for the whole app (20px, 2px stroke)
     ==================================================================== */
  var ICONS = {
    search: 'M21 21l-4.3-4.3M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0z',
    x: 'M6 6l12 12M6 18L18 6',
    back: 'M15 5l-7 7 7 7',
    forward: 'M9 5l7 7-7 7',
    up: 'M6 15l6-6 6 6',
    down: 'M6 9l6 6 6-6',
    more: 'M5 12h.01M12 12h.01M19 12h.01',
    heart: 'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8z',
    hide: 'M4 12a8 8 0 1 0 16 0 8 8 0 1 0-16 0M6.3 6.3l11.4 11.4',
    check: 'M5 12l5 5L20 7',
    plus: 'M12 5v14M5 12h14',
    minus: 'M5 12h14',
    locate: 'M12 2v3M12 19v3M2 12h3M19 12h3M5 12a7 7 0 1 0 14 0 7 7 0 1 0-14 0M10 12a2 2 0 1 0 4 0 2 2 0 1 0-4 0',
    layers: 'M12 3l9 5-9 5-9-5 9-5zM3 12l9 5 9-5M3 16l9 5 9-5',
    pin: 'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0zM9 10a3 3 0 1 0 6 0 3 3 0 1 0-6 0',
    user: 'M20 21a8 8 0 1 0-16 0M12 13a4 4 0 1 0 0-8 4 4 0 0 0 0 8z',
    filter: 'M4 6h16M7 12h10M10 18h4',
    sliders: 'M4 7h10M18 7h2M4 17h4M12 17h8M14 4v6M8 14v6',
    list: 'M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01',
    select: 'M9 6h12M9 12h12M9 18h12M3 5h2v2H3zM3 11h2v2H3zM3 17h2v2H3z',
    moon: 'M20 15.6A9 9 0 0 1 8.4 4 9 9 0 1 0 20 15.6z',
    sun: 'M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6l1.4 1.4M17 17l1.4 1.4M5.6 18.4L7 17M17 7l1.4-1.4M8 12a4 4 0 1 0 8 0 4 4 0 1 0-8 0',
    calendar: 'M4 6h16v15H4zM8 3v5M16 3v5M4 11h16',
    seat: 'M7 12V7a5 5 0 0 1 10 0v5M5 12h14v5H5zM6 17v4M18 17v4',
    map: 'M3 6l6-2 6 2 6-2v14l-6 2-6-2-6 2zM9 4v14M15 6v14',
    share: 'M4 12v7a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-7M12 15V3M8 7l4-4 4 4',
    folder: 'M3 7h6l2 2h10v10H3z',
    folderPlus: 'M3 7h6l2 2h10v10H3zM12 11v6M9 14h6',
    trash: 'M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14M10 11v6M14 11v6',
    copy: 'M9 9h11v11H9zM5 15H4V4h11v1',
    image: 'M3 5h18v14H3zM3 16l5-5 4 4 3-3 6 6M15 9h.01',
    images: 'M7 7h14v12H7zM3 17V3h14M10 15l3-3 3 3 2-2 3 3',
    info: 'M12 11v6M12 7h.01M2 12a10 10 0 1 0 20 0 10 10 0 1 0-20 0',
    help: 'M9.5 9a2.5 2.5 0 1 1 3.5 2.3c-.8.4-1 1-1 1.7M12 17h.01M2 12a10 10 0 1 0 20 0 10 10 0 1 0-20 0',
    external: 'M14 4h6v6M20 4l-9 9M19 14v6H4V5h6',
    translate: 'M4 5h10M9 3v2M12 5c-1 4-4 7-8 9M6 8c1 3 3 5 6 6M13 21l4-10 4 10M14.5 17h5',
    chevronRight: 'M9 6l6 6-6 6',
    chevronLeft: 'M15 6l-6 6 6 6',
    chevronDown: 'M6 9l6 6 6-6',
    chevronUp: 'M6 15l6-6 6 6',
    expand: 'M4 14v6h6M20 10V4h-6M4 20l6-6M20 4l-6 6',
    collapse: 'M10 14H4v6M14 10h6V4M4 20l6-6M20 4l-6 6',
    grip: 'M8 6h.01M16 6h.01M8 12h.01M16 12h.01M8 18h.01M16 18h.01',
    rail: 'M3 7h18M3 12h18M3 17h18',
    train: 'M6 3h12a2 2 0 0 1 2 2v9a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4V5a2 2 0 0 1 2-2zM4 10h16M8 21l1-3M16 21l-1-3M8.5 14.5h.01M15.5 14.5h.01',
    landmark: 'M3 21h18M5 21V10M19 21V10M9 21v-6h6v6M2 10l10-7 10 7',
    bookmark: 'M6 3h12v18l-6-4-6 4z',
    star: 'M12 3l2.8 5.8 6.2.9-4.5 4.4 1.1 6.2L12 17.4l-5.6 2.9 1.1-6.2L3 9.7l6.2-.9z',
    starFill: 'M12 3l2.8 5.8 6.2.9-4.5 4.4 1.1 6.2L12 17.4l-5.6 2.9 1.1-6.2L3 9.7l6.2-.9z',
    globe: 'M2 12a10 10 0 1 0 20 0 10 10 0 1 0-20 0M2 12h20M12 2a15 15 0 0 1 0 20 15 15 0 0 1 0-20',
    download: 'M12 3v12M7 10l5 5 5-5M4 21h16',
    upload: 'M12 21V9M7 14l5-5 5 5M4 3h16',
    reset: 'M3 12a9 9 0 1 0 3-6.7M3 4v5h5',
    logout: 'M10 4H4v16h6M14 8l4 4-4 4M8 12h10',
    offline: 'M3 3l18 18M9 9a9 9 0 0 1 10 0M6 12a7 7 0 0 1 3-2M12 16h.01M16 12a6 6 0 0 0-1-1',
    refresh: 'M20 12a8 8 0 1 1-2.3-5.7M20 4v5h-5',
    warning: 'M12 3l10 18H2zM12 10v5M12 18h.01',
    undo: 'M9 14l-4-4 4-4M5 10h9a5 5 0 0 1 0 10h-3',
    drag: 'M8 9h8M8 15h8',
    keyboard: 'M3 6h18v12H3zM7 10h.01M11 10h.01M15 10h.01M7 14h10',
    gear: 'M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6zM19.4 15a1.6 1.6 0 0 0 .3 1.8l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1.6 1.6 0 0 0-1.8-.3 1.6 1.6 0 0 0-1 1.5V21a2 2 0 1 1-4 0v-.1A1.6 1.6 0 0 0 9 19.4a1.6 1.6 0 0 0-1.8.3l-.1.1a2 2 0 1 1-2.8-2.8l.1-.1a1.6 1.6 0 0 0 .3-1.8 1.6 1.6 0 0 0-1.5-1H3a2 2 0 1 1 0-4h.1A1.6 1.6 0 0 0 4.6 9a1.6 1.6 0 0 0-.3-1.8l-.1-.1a2 2 0 1 1 2.8-2.8l.1.1a1.6 1.6 0 0 0 1.8.3H9a1.6 1.6 0 0 0 1-1.5V3a2 2 0 1 1 4 0v.1a1.6 1.6 0 0 0 1 1.5 1.6 1.6 0 0 0 1.8-.3l.1-.1a2 2 0 1 1 2.8 2.8l-.1.1a1.6 1.6 0 0 0-.3 1.8V9a1.6 1.6 0 0 0 1.5 1H21a2 2 0 1 1 0 4h-.1a1.6 1.6 0 0 0-1.5 1z',
    yen: 'M12 12.5L6.5 4M12 12.5L17.5 4M12 12.5V20M8 13.5h8M8 16.5h8',
    trophy: 'M7 4h10v5a5 5 0 0 1-10 0zM7 6H4v2a3 3 0 0 0 3 3M17 6h3v2a3 3 0 0 1-3 3M9 20h6M12 14v6',
    cutlery: 'M6 3v7a2 2 0 0 0 4 0V3M8 10v11M17 3c-1.5 1.5-2 3-2 5v4h4V8c0-2-.5-3.5-2-5zM17 12v9',
    lock: 'M6 11h12v10H6zM9 11V7a3 3 0 0 1 6 0v4',
    google: 'M21 12.2c0-.7-.1-1.3-.2-1.9H12v3.6h5.1a4.4 4.4 0 0 1-1.9 2.9v2.4h3.1c1.8-1.7 2.7-4.1 2.7-7z',
    grid: 'M4 4h7v7H4zM13 4h7v7h-7zM4 13h7v7H4zM13 13h7v7h-7z',
    sortAsc: 'M4 6h12M4 12h8M4 18h4M18 8v10M15 15l3 3 3-3',
    chopsticks: 'M4 20L18 3M8 22L21 5M3 14l6 5',
    clock: 'M2 12a10 10 0 1 0 20 0 10 10 0 1 0-20 0M12 7v5l3 2',
    walk: 'M13 4h.01M10 21l2-6 3 3v3M9 12l3-3 3 2 2 1M12 9l-2 4-3 1',
    legend: 'M4 5h4v4H4zM4 15h4v4H4zM11 7h9M11 17h9'
  };
  App.icons = ICONS;
  /** App.icon('heart', {cls, fill}) → SVG markup string, aria-hidden. */
  App.icon = function (name, opts) {
    var d = ICONS[name] || ICONS.info;
    var cls = 'ic' + (opts && opts.cls ? ' ' + opts.cls : '');
    var fill = opts && opts.fill ? ' style="fill:currentColor;stroke:none"' : '';
    return '<svg class="' + cls + '" viewBox="0 0 24 24" aria-hidden="true" focusable="false"' + fill + '><path d="' + d + '"/></svg>';
  };

  /* ========================================================================
     i18n
     ==================================================================== */
  var I18N = window.I18N = {};
  var _tables = { en: {}, ja: {}, tw: {} };
  var _zhKeys = new Set();

  /** I18N.register({en:{'简体':'English'}, ja:{...}, tw:{...}}) — merges. */
  I18N.register = function (tables) {
    if (!tables) return;
    Object.keys(tables).forEach(function (lang) {
      if (!_tables[lang]) _tables[lang] = {};
      var src = tables[lang] || {};
      Object.keys(src).forEach(function (k) {
        _tables[lang][k] = src[k];
        _zhKeys.add(k);
      });
    });
  };
  /** I18N.keys() → every registered zh key (for the OpenCC tw pass). */
  I18N.keys = function () { return Array.from(_zhKeys).sort(); };
  I18N.tables = function () { return _tables; };
  I18N.lang = function () { return App.state ? App.state.lang : 'zh'; };

  function interpolate(s, params) {
    if (!params) return s;
    return s.replace(/\{(\w+)\}/g, function (m, k) {
      return params[k] === undefined || params[k] === null ? m : String(params[k]);
    });
  }

  /**
   * t(zhKey, params) — the only rendering entry for UI copy. Keys are the
   * Simplified Chinese strings; a missing translation falls back to zh.
   * Params fill {name} placeholders; never concatenate sentences.
   */
  var t = window.t = function (key, params) {
    var lang = I18N.lang();
    _zhKeys.add(key);
    var table = _tables[lang];
    var s;
    if (lang !== 'zh' && table && table[key] !== undefined) s = table[key];
    else if (lang !== 'zh' && window.Business && typeof window.Business.localizeText === 'function') s = window.Business.localizeText(key);
    else s = key;
    return interpolate(String(s), params);
  };
  I18N.t = t;

  /** setLang('zh'|'tw'|'en'|'ja') — html lang + state + re-render. */
  I18N.setLang = function (lang) {
    if (!/^(zh|tw|en|ja)$/.test(lang)) lang = 'zh';
    document.documentElement.lang = util.langLocale(lang);
    if (App.state && App.state.lang !== lang) App.set({ lang: lang });
    else if (App.state) App.requestRender('lang');
    App.emit('lang:changed', lang);
  };
  /** setFontScale(100|115|130) — html{font-size} only (I18N-02). */
  I18N.setFontScale = function (fs) {
    fs = Number(fs); if ([100, 115, 130].indexOf(fs) < 0) fs = 100;
    document.documentElement.setAttribute('data-fs', String(fs));
    if (App.state && App.state.fontScale !== fs) App.set({ fontScale: fs });
    App.layout.schedule();
  };
  App.i18n = I18N;

  // The build-time UI table (ui/i18n/ui-strings.json, emitted by map.py as a
  // direct `window.UI_I18N_TABLES = {...}` assignment — not a placeholder),
  // registered first so a module's inline register() can still override.
  if (window.UI_I18N_TABLES) { try { I18N.register(window.UI_I18N_TABLES); } catch (e) { console.error(e); } }
  // Core copy (shared chrome) lives in ui/i18n/ui-strings.json with every
  // other UI string; it arrived above as window.UI_I18N_TABLES.

  /* ========================================================================
     emoji — Apple-style PNGs from assets/emoji (manifest.js), text fallback
     ==================================================================== */
  var emoji = App.emoji = {};
  // Production: the PNG set is docs/emoji/ (build_emoji_cache.py) via the
  // EMOJI_MAP manifest Business carries; anything not pre-cached comes from
  // emojicdn (M-144: with CORS so the SW's ext cache is billed real bytes).
  emoji.src = function (ch) {
    var B = window.Business;
    if (!B || typeof B.emojiSrc !== 'function') return null;
    return B.emojiSrc(ch);
  };
  emoji.isLocal = function (ch) {
    var B = window.Business;
    return !!(B && typeof B.emojiLocal === 'function' && B.emojiLocal(ch));
  };
  /**
   * emoji.img(char, size) → markup. <img class="emj" alt=""> when the PNG is
   * in the manifest, else a text <span class="emj-text"> so nothing breaks.
   * size: CSS px (optional) — sets width/height inline.
   */
  var _emjMemo = Object.create(null);           // map coreRequest #5: one manifest lookup per (char,size,cls)
  emoji.img = function (ch, size, cls) {
    if (!ch) return '';
    var mk = ch + '|' + (size || '') + '|' + (cls || '');
    var hit = _emjMemo[mk];
    if (hit !== undefined) return hit;
    var src = emoji.src(ch);
    var style = size ? ' style="width:' + size + 'px;height:' + size + 'px"' : '';
    var extra = cls ? ' ' + cls : '';
    var cors = (src && !emoji.isLocal(ch)) ? ' crossorigin="anonymous"' : '';
    var out = src
      ? '<img class="emj' + extra + '" alt="" draggable="false"' + cors + ' src="' + src + '"' + style + '>'
      : '<span class="emj-text' + extra + '" aria-hidden="true"' + (size ? ' style="font-size:' + Math.round(size * .85) + 'px"' : '') + '>' + util.esc(ch) + '</span>';
    _emjMemo[mk] = out;
    return out;
  };
  emoji.url = function (ch) { return emoji.src(ch); };
  /** emoji.html(text) — replace emoji runs inside a string with img tags. */
  var EMOJI_RE = /(\p{Extended_Pictographic}(?:️|‍\p{Extended_Pictographic}|[\u{1F3FB}-\u{1F3FF}])*|[\u{1F1E6}-\u{1F1FF}]{2})/gu;
  emoji.html = function (text, size) {
    return util.esc(text).replace(EMOJI_RE, function (m) { return emoji.img(m, size); });
  };
  emoji.isPure = function (s) {
    if (!s) return false;
    var stripped = s.replace(EMOJI_RE, '');
    return stripped.length === 0 && Array.from(s.matchAll(EMOJI_RE)).length === 1;
  };

  /* ========================================================================
     motion — durations from tokens, reduced-motion, FLIP, transition waits,
     and the LAY-05 "don't restore scrollTop until geometry settles" queue
     ==================================================================== */
  var motion = App.motion = {};
  var _mq = window.matchMedia ? window.matchMedia('(prefers-reduced-motion: reduce)') : null;
  motion.reduced = !!(_mq && _mq.matches);
  if (_mq && _mq.addEventListener) _mq.addEventListener('change', function (e) { motion.reduced = e.matches; });

  function cssMs(name, fallback) {
    var v = getComputedStyle(document.documentElement).getPropertyValue(name).trim();
    if (!v) return fallback;
    if (/ms$/.test(v)) return parseFloat(v);
    if (/s$/.test(v)) return parseFloat(v) * 1000;
    var n = parseFloat(v); return isNaN(n) ? fallback : n;
  }
  motion.readTokens = function () {
    motion.micro = motion.reduced ? 0 : cssMs('--m-micro', 160);
    motion.standard = motion.reduced ? 0 : cssMs('--m-standard', 240);
    motion.sheet = motion.reduced ? 0 : cssMs('--m-sheet', 320);
    motion.fly = motion.reduced ? 0 : cssMs('--m-fly', 400);
    motion.toastMs = cssMs('--m-toast-ms', 9000);
    motion.settleMs = cssMs('--viewport-settle-ms', 180);
    motion.easeStandard = 'cubic-bezier(.2,.8,.2,1)';
    motion.easeOut = 'ease-out';
  };

  /** afterTransition(el, {prop, timeout}) → Promise; resolves on transitionend or timeout. */
  motion.afterTransition = function (el, opts) {
    opts = opts || {};
    var dur = opts.timeout !== undefined ? opts.timeout : (motion.standard + 60);
    return new Promise(function (resolve) {
      if (!el || dur <= 0 || motion.reduced) { resolve(); return; }
      var done = false;
      var tm = setTimeout(finish, dur);
      function finish() { if (done) return; done = true; clearTimeout(tm); el.removeEventListener('transitionend', onEnd); resolve(); }
      function onEnd(e) { if (e.target !== el) return; if (opts.prop && e.propertyName !== opts.prop) return; finish(); }
      el.addEventListener('transitionend', onEnd);
    });
  };

  /**
   * flip(el, fromRect, {duration, easing}) — animate el from a previous
   * rect to its current layout position with transform only.
   */
  motion.flip = function (el, from, opts) {
    if (!el || !from) return Promise.resolve();
    var to = el.getBoundingClientRect();
    var dur = (opts && opts.duration !== undefined) ? opts.duration : motion.standard;
    if (dur <= 0 || motion.reduced) return Promise.resolve();
    var dx = from.left - to.left, dy = from.top - to.top;
    var sx = from.width / (to.width || 1), sy = from.height / (to.height || 1);
    el.style.transformOrigin = 'top left';
    el.style.transition = 'none';
    el.style.transform = 'translate(' + dx + 'px,' + dy + 'px) scale(' + sx + ',' + sy + ')';
    el.style.willChange = 'transform';
    return new Promise(function (resolve) {
      util.raf(function () {
        el.style.transition = 'transform ' + dur + 'ms ' + ((opts && opts.easing) || motion.easeStandard);
        el.style.transform = '';
        motion.afterTransition(el, { prop: 'transform', timeout: dur + 60 }).then(function () {
          el.style.transition = ''; el.style.willChange = ''; el.style.transformOrigin = '';
          resolve();
        });
      });
    });
  };

  // Geometry-busy gate (LAY-05): containers marks height/width transitions;
  // anyone restoring scrollTop / focus waits via afterGeometry().
  var _geomBusy = 0, _geomQueue = [];
  motion.geometryBusy = function (promise) {
    _geomBusy += 1;
    var release = function () { _geomBusy = Math.max(0, _geomBusy - 1); if (_geomBusy === 0) flushGeom(); };
    Promise.resolve(promise).then(release, release);
    return release;
  };
  motion.isGeometryBusy = function () { return _geomBusy > 0; };
  function flushGeom() {
    var q = _geomQueue; _geomQueue = [];
    q.forEach(function (fn) { try { fn(); } catch (e) { console.error(e); } });
  }
  /** afterGeometry(fn) — run now if idle, else after every pending geometry transition. */
  motion.afterGeometry = function (fn) {
    if (_geomBusy === 0) { fn(); return; }
    _geomQueue.push(fn);
  };

  /* ========================================================================
     state tree, event bus, render scheduler
     ==================================================================== */
  App.defaultState = function () {
    return {
      lang: 'zh',
      fontScale: 100,
      demo: null,                       // 'offline' | 'update' | null (URL ?demo=)
      layout: { mode: 'narrow', W: 402, H: 874, U: { x: 0, y: 0, w: 402, h: 874 }, occ: 0, mapRect: { x: 0, y: 0, w: 402, h: 794 }, compact: false, severe: false },
      sheet: { state: 'collapsed', tab: 'results', dragging: false, height: 80 },
      columns: { leftOpen: true, userLeftPreference: null, autoCollapsed: false, detailOpen: false, detailPaused: false },
      selected: { id: null, origin: null, anchor: null },
      search: { active: false, query: '', activeIndex: -1, placeFilter: null, dropLoc: false },
      filters: {
        // Seeded to the full key lists by the adapter once config is loaded; the
        // sets are literal from then on (empty = cleared = no results).
        region: null, ratingMin: 3.4, budgets: new Set(),
        cuisines: new Set(),
        awards: new Set(), bookableOnly: false, favOnly: false,
        hideBlack: true, hideForeign: true, gcalOnly: false
      },
      sort: 'rating',
      user: { fav: new Set(), black: new Set(), bookmarks: [] },
      multi: { active: false, ids: new Set(), scope: 'results' },
      saved: { groupBy: 'city', openGroups: null, onlyList: null },
      layers: { long: false, city: false, landmarks: true, pins: true, hiddenLandmarks: false, loading: {}, error: {} },
      overlay: { kind: null, payload: null },
      toast: null,                      // {id, kind, text, count, undo, action:{label,run}, remainingMs, paused}
      notices: { offline: false, newVersion: false, oov: { shown: false, dismissedForever: false, visible: false } },
      mapView: { center: [35.6812, 139.7671], zoom: 14 },
      userDraggedMap: false,
      signedIn: false,
      // mirrored from Business by adapter.js (read-only for modules)
      account: { signedIn: false, email: '', name: '', picture: '', message: '', messageColor: '' },
      sync: { text: '', kind: '', dirty: false, retryVisible: false, storageInfo: '', hintDismissed: true },
      detail: { scrollTo: null, translation: 'zh', candidatesOpen: true },
      // Seeded by adapter.js from Business at boot. Declared here so a module
      // that reads them before boot (or in a no-adapter path) gets the empty
      // shape rather than undefined.
      nearby: { active: false, planning: null, pending: false, fix: null },
      install: { standalone: false, installed: false, canPrompt: false, ios: false, snackEligible: false },
      buildMeta: { appVersion: '', scrapedAt: '', latestScrape: '' },
      nativeSettings: null,
      filtersUi: { scrollTo: null, openGroups: new Set(['正餐']), cuisinesOpen: true }
    };
  };

  App.state = App.defaultState();
  var _listeners = {};           // event → [fn]
  var _subs = [];                // state subscribers
  var _pendingChanged = new Set();
  var _renderScheduled = false;
  var _silentDepth = 0;

  App.get = function () { return App.state; };

  function mergeInto(target, patch, path, changed) {
    Object.keys(patch).forEach(function (k) {
      var pv = patch[k], tv = target[k];
      var p = path ? path + '.' + k : k;
      if (util.isPlainObject(pv) && util.isPlainObject(tv)) {
        mergeInto(tv, pv, p, changed);
      } else {
        var same = (pv === tv) || (pv instanceof Set && tv instanceof Set && util.setEq(pv, tv));
        if (!same) { target[k] = pv; changed.add(p); changed.add(p.split('.')[0]); }
      }
    });
  }

  /**
   * App.set(patch, {silent}) — deep-merges plain objects, replaces Sets,
   * arrays, primitives and null. Pass a *new* Set to change one (use
   * util.setWith / setWithout / setToggle). Schedules a render unless silent.
   * Returns the Set of changed paths.
   */
  App.set = function (patch, opts) {
    var changed = new Set();
    if (patch) mergeInto(App.state, patch, '', changed);
    if (changed.size) {
      changed.forEach(function (c) { _pendingChanged.add(c); });
      App.emit('state:changed', changed);
      if (!(opts && opts.silent) && _silentDepth === 0) scheduleRender();
    }
    return changed;
  };

  /** App.replaceState(state) — used by scenes / snapshot restore. */
  App.replaceState = function (state) {
    App.state = state;
    _pendingChanged.add('*');
    scheduleRender();
  };

  App.requestRender = function (reason) { _pendingChanged.add(reason || '*'); scheduleRender(); };

  function scheduleRender() {
    if (_renderScheduled) return;
    _renderScheduled = true;
    util.raf(flushRender);
  }

  function flushRender() {
    _renderScheduled = false;
    var changed = _pendingChanged; _pendingChanged = new Set();
    var state = App.state;
    // derived layout first so modules see the final geometry
    if (changed.has('*') || changed.has('layout') || changed.has('sheet') || changed.has('columns') ||
        changed.has('selected') || changed.has('search') || changed.has('overlay') || changed.has('fontScale')) {
      App.layout.derive(state, changed);
    }
    document.documentElement.setAttribute('data-mode', state.layout.mode);
    document.documentElement.setAttribute('data-sheet', state.sheet.state);
    document.documentElement.toggleAttribute('data-fold-cover', !!state.layout.foldCover);
    document.documentElement.setAttribute('data-list-tab', state.sheet.tab);
    document.documentElement.toggleAttribute('data-search-active', !!state.search.active);
    document.documentElement.toggleAttribute('data-overlay', !!state.overlay.kind);
    document.documentElement.toggleAttribute('data-multi', !!state.multi.active);
    App._moduleOrder.forEach(function (name) {
      var mod = App.modules[name];
      if (mod && typeof mod.render === 'function') {
        try { mod.render(state, changed); } catch (e) { console.error('[render:' + name + ']', e); }
      }
    });
    _subs.forEach(function (fn) { try { fn(state, changed); } catch (e) { console.error(e); } });
    App.nav.sync(state);
    App.emit('render', changed);
  }
  App.flushNow = function () { if (_renderScheduled) flushRender(); };

  /** App.subscribe(fn(state, changedSet)) → unsubscribe. Runs after modules' render(). */
  App.subscribe = function (fn) {
    _subs.push(fn);
    return function () { var i = _subs.indexOf(fn); if (i >= 0) _subs.splice(i, 1); };
  };

  /** App.on(event, fn) → off(). App.emit(event, payload). App.once(event, fn). */
  App.on = function (ev, fn) {
    (_listeners[ev] = _listeners[ev] || []).push(fn);
    return function () { var a = _listeners[ev] || []; var i = a.indexOf(fn); if (i >= 0) a.splice(i, 1); };
  };
  App.once = function (ev, fn) { var off = App.on(ev, function (p) { off(); fn(p); }); return off; };
  App.emit = function (ev, payload) {
    var a = (_listeners[ev] || []).slice();
    a.forEach(function (fn) { try { fn(payload, ev); } catch (e) { console.error('[emit:' + ev + ']', e); } });
    var star = (_listeners['*'] || []).slice();
    star.forEach(function (fn) { try { fn(payload, ev); } catch (e) { console.error(e); } });
  };
  /** changedAny(changed, ['filters','user']) — true if any key or '*' is in the set. */
  App.changedAny = function (changed, keys) {
    if (!changed || changed.has('*')) return true;
    for (var i = 0; i < keys.length; i++) if (changed.has(keys[i])) return true;
    return false;
  };

  // ---- snapshot (JSON-safe) — Sets → {__set:[...]}
  App.snapshot = function (state) {
    state = state || App.state;
    return JSON.parse(JSON.stringify(state, function (k, v) {
      if (v instanceof Set) return { __set: Array.from(v) };
      return v;
    }));
  };
  App.restoreSnapshot = function (snap) {
    var revive = function (v) {
      if (v && typeof v === 'object') {
        if (Array.isArray(v.__set) && Object.keys(v).length === 1) return new Set(v.__set);
        if (Array.isArray(v)) return v.map(revive);
        var o = {}; Object.keys(v).forEach(function (k) { o[k] = revive(v[k]); }); return o;
      }
      return v;
    };
    var base = App.defaultState();
    var restored = revive(snap);
    // keep any keys a newer default has that the snapshot lacks
    Object.keys(base).forEach(function (k) { if (restored[k] === undefined) restored[k] = base[k]; });
    App.replaceState(restored);
  };

  /* ========================================================================
     layout — LAY-01 usable rect U, LAY-02 columns, LAY-03/04 sheet heights,
     mapRect, ENV-02 coalesced resize + settle
     ==================================================================== */
  var layout = App.layout = {};
  var CFG = {                           // mirrors css/tokens.css + DESIGN-TOKENS.json layout
    narrowLt: 750, wideGte: 1100, detailRatioSwitch: 450,
    compactHLte: 620, severeHLte: 419,
    topbarMid: 56, topbarWide: 60, rail: 56,
    wideLeft: { min: 344, ratio: .22, max: 384 }, wideDetail: { min: 400, ratio: .27, max: 480 },
    midLeft: { min: 300, ratio: .35, max: 344 }, midDetail: { min: 320, ratio: .40, max: 380 },
    fullThreeColumnMapMin: 480,
    sheet: { collapsed: 56, resultsNormal: .49, resultsCompact: .63, detailSmall: .61, detailLarge: .65, detailCompact: .70,
             filterNormal: .72, filterCompact: .82, expandedMap: 170, minText: 24, minControl: 44, minSuggestion: 56 },
    layers: { width: 360, margin: 16, gap: 8, headerMin: 44, rowMin: 56 }
  };
  layout.CFG = CFG;

  layout.mode = function (W) {
    W = W === undefined ? App.state.layout.W : W;
    return W < CFG.narrowLt ? 'narrow' : (W < CFG.wideGte ? 'mid' : 'wide');
  };

  // Stable screen geometry keeps this profile independent of keyboard/toolbars.
  layout.isFoldCover = function (W) {
    var sc = window.screen, touch = navigator.maxTouchPoints > 0 || window.matchMedia('(pointer: coarse)').matches;
    if (!sc || !touch) return false;
    var short = Math.min(sc.width, sc.height), long = Math.max(sc.width, sc.height);
    return Math.abs(short - 475) <= 1 && Math.abs(long - 751) <= 1 && Math.abs(W - 475) <= 1 && layout.mode(W) === 'narrow';
  };

  // safe-area probe: reads env() once per measure
  var _probe = null;
  function safeArea() {
    if (!_probe) {
      _probe = document.createElement('div');
      _probe.style.cssText = 'position:fixed;left:0;top:0;width:0;height:0;visibility:hidden;pointer-events:none;' +
        // --app-inset-top is the Android shell's belt-and-braces copy of the top inset
        // (STANDARDS §1.2a / bug A-1): a WebView build that reports 0 for
        // safe-area-inset-top on a device that really does draw the page under a 40dp
        // status bar would otherwise put the top chrome under the clock. env() stays the
        // primary source — max() of the two means a correct env() and a correct variable
        // agree and nothing is padded twice. The variable is unset in every browser, where
        // var(...,0px) makes this identical to the plain env() read.
        'padding-top:max(env(safe-area-inset-top,0px),var(--app-inset-top,0px));' +
        'padding-right:env(safe-area-inset-right,0px);' +
        'padding-bottom:env(safe-area-inset-bottom,0px);padding-left:env(safe-area-inset-left,0px)';
      document.documentElement.appendChild(_probe);
    }
    var cs = getComputedStyle(_probe);
    return { top: parseFloat(cs.paddingTop) || 0, right: parseFloat(cs.paddingRight) || 0,
             bottom: parseFloat(cs.paddingBottom) || 0, left: parseFloat(cs.paddingLeft) || 0 };
  }

  var _insets = {};   // owner → {top,right,bottom,left} extra map obstructions (px)
  /** setInset(owner, {top,right,bottom,left}|null) — extra obstruction over the map (e.g. narrow search chrome). */
  layout.setInset = function (owner, rect) {
    if (rect) _insets[owner] = rect; else delete _insets[owner];
    layout.schedule();
  };

  var _sheetMeasure = null;
  /** registerSheetMeasure(fn(state) → {F, C}) — containers supplies real fixed-chrome / min-content heights (LAY-04). */
  layout.registerSheetMeasure = function (fn) { _sheetMeasure = fn; };

  /**
   * setTopbarH(px) — containers reports what the mid/wide bar actually needs
   * once its row has been laid out. LAY-04 grows the panel rather than cutting
   * the text, and at 200% the search field alone is 94px tall, so the CFG
   * constant is a floor, not a ceiling. Columns and mapRect follow it.
   */
  var _topbarH = 0;
  layout.setTopbarH = function (px) {
    px = Math.max(0, Math.round(px || 0));
    if (px === _topbarH) return;
    _topbarH = px;
    App.requestRender('layout');
  };

  /**
   * measure() — reads the viewport once (LAY-01) and stores W/H/U in state.
   * Called at boot and from the coalesced resize handler. Returns true if
   * geometry actually changed (ENV-02: only then do we rebuild anything).
   */
  layout.measure = function () {
    var doc = document.documentElement;
    var W = doc.clientWidth || window.innerWidth, Hfull = doc.clientHeight || window.innerHeight;
    var vv = window.visualViewport;
    var x = 0, y = 0, w = W, h = Hfull;
    if (vv) {
      x = Math.max(0, vv.offsetLeft || 0); y = Math.max(0, vv.offsetTop || 0);
      w = Math.min(W - x, vv.width || W); h = Math.min(Hfull - y, vv.height || Hfull);
    }
    var sa = safeArea();
    var U = { x: Math.round(x + sa.left), y: Math.round(y + sa.top),
              w: Math.round(Math.max(0, w - sa.left - sa.right)), h: Math.round(Math.max(0, h - sa.top - sa.bottom)) };
    // ENV-02 §1 (geometry path): the band of the LAYOUT viewport that the visual
    // viewport no longer covers — Safari's expanded toolbars, the software
    // keyboard. `#app` is `position: fixed; inset: 0`, i.e. the layout viewport,
    // so every `bottom: 0` child sits *under* that band unless it is lifted by
    // exactly this much. It is 0 whenever the two viewports agree, so nothing
    // moves at rest; the safe-area inset is deliberately NOT folded in (the
    // fixed rows already pay it through their own `padding-bottom`).
    var occ = Math.round(Math.max(0, Hfull - (y + h)));
    var cur = App.state.layout, foldCover = layout.isFoldCover(W);
    var same = !!cur.foldCover === foldCover && cur.W === W && cur.H === U.h && cur.occ === occ &&
               cur.U && cur.U.x === U.x && cur.U.y === U.y && cur.U.w === U.w && cur.U.h === U.h;
    if (same) return false;
    App.set({ layout: { W: W, H: U.h, U: U, occ: occ, mode: layout.mode(W), foldCover: foldCover, compact: U.h <= CFG.compactHLte, severe: U.h <= CFG.severeHLte } });
    App.emit('layout:changed', App.state.layout);
    return true;
  };

  /** columns(state) → {leftW, detailW, railW, topbarH, detailPaused, autoCollapsed} per LAY-02. */
  layout.columns = function (state) {
    state = state || App.state;
    var L = state.layout, C = state.columns, W = L.W, mode = L.mode;
    if (mode === 'narrow') return { leftW: 0, detailW: 0, railW: 0, topbarH: 0, detailPaused: false, autoCollapsed: false, leftVisible: false };
    var cl = mode === 'wide' ? CFG.wideLeft : CFG.midLeft;
    var cd = mode === 'wide' ? CFG.wideDetail : CFG.midDetail;
    var fullLeft = util.clamp(Math.round(W * cl.ratio), cl.min, cl.max);
    var detailW = C.detailOpen ? util.clamp(Math.round(W * cd.ratio), cd.min, cd.max) : 0;
    var wantLeft = C.userLeftPreference === null ? true : C.userLeftPreference === 'open';
    var autoCollapsed = false, detailPaused = false, leftW;
    if (!wantLeft) leftW = CFG.rail;
    else if (!C.detailOpen) leftW = fullLeft;
    else if (mode === 'mid') {
      // mid: opening detail collapses the full left column by default (LAY-02)
      if (C.userLeftPreference === 'open') { detailPaused = true; leftW = fullLeft; detailW = 0; }
      else { leftW = CFG.rail; autoCollapsed = true; }
    } else {
      if (W - fullLeft - detailW >= CFG.fullThreeColumnMapMin) leftW = fullLeft;
      else if (C.userLeftPreference === 'open') { detailPaused = true; leftW = fullLeft; detailW = 0; }
      else { leftW = CFG.rail; autoCollapsed = true; }
    }
    return { leftW: leftW, detailW: detailW, railW: CFG.rail, fullLeft: fullLeft,
             topbarH: Math.max(mode === 'wide' ? CFG.topbarWide : CFG.topbarMid, _topbarH),
             detailPaused: detailPaused, autoCollapsed: autoCollapsed, leftVisible: leftW > CFG.rail };
  };

  /**
   * sheetTarget(sheetState, state) → px height for the narrow bottom sheet
   * (LAY-03 branches, LAY-04 fallback). Returns {h, full, F, C}.
   */
  layout.sheetTarget = function (sheetState, state) {
    state = state || App.state;
    var H = state.layout.H, W = state.layout.W, compact = state.layout.compact, S = CFG.sheet;
    var target;
    switch (sheetState) {
      case 'collapsed': target = S.collapsed; break;
      case 'browse': target = H * (compact ? S.resultsCompact : S.resultsNormal); break;
      case 'detail': target = compact ? H * S.detailCompact : H * (W < CFG.detailRatioSwitch ? S.detailSmall : S.detailLarge); break;
      case 'filter': target = H * (compact ? S.filterCompact : S.filterNormal); break;
      case 'expanded': target = H - S.expandedMap; break;
      case 'full': target = H; break;
      default: target = S.collapsed;
    }
    target = Math.round(target);
    var F = 0, C = 0;
    if (_sheetMeasure && sheetState !== 'collapsed') {
      try { var m = _sheetMeasure(sheetState, state) || {}; F = m.F || 0; C = m.C || 0; } catch (e) { console.error(e); }
    }
    var need = F + C;
    var full = need > H;
    var h = full ? H : Math.min(H, Math.max(target, need));
    return { h: h, full: full, F: F, C: C, target: target };
  };

  /** mapRect(state) → visible map rectangle inside U after panels/columns/insets (MAP-02 §6). */
  layout.mapRect = function (state) {
    state = state || App.state;
    var U = state.layout.U, mode = state.layout.mode;
    var top = 0, right = 0, bottom = 0, left = 0;
    if (mode === 'narrow') {
      bottom = state.search.active ? U.h : (state.sheet.height || 0);
    } else {
      var c = layout.columns(state);
      top = c.topbarH; left = c.leftW; right = c.detailW;
    }
    Object.keys(_insets).forEach(function (k) {
      var r = _insets[k]; top = Math.max(top, r.top || 0); right = Math.max(right, r.right || 0);
      bottom = Math.max(bottom, r.bottom || 0); left = Math.max(left, r.left || 0);
    });
    var h = Math.max(0, U.h - top - bottom), w = Math.max(0, U.w - left - right);
    // LAY-04 (containers coreRequest #2): a map band too short to carry its own
    // attribution is a tile sliver, which the rule forbids. Two owners can each
    // publish a legal inset and still add up to one, so clamp here where both are
    // visible: first try to give the band its 44px back from the top inset, and if
    // the screen truly cannot afford it, drop the band to zero instead of a sliver.
    var MIN_BAND = 44;
    if (mode === 'narrow' && h > 0 && h < MIN_BAND) {
      var give = Math.min(top, MIN_BAND - h);
      top -= give; h += give;
      if (h < MIN_BAND) { h = 0; w = 0; }
    }
    return { x: U.x + left, y: U.y + top, w: w, h: h };
  };

  /** derive(state) — recompute sheet height / columns / mapRect and publish CSS variables. Called every render pass. */
  layout.derive = function (state, changed) {
    var root = document.documentElement.style;
    var U = state.layout.U;
    root.setProperty('--U-w', U.w + 'px'); root.setProperty('--U-h', U.h + 'px');
    root.setProperty('--U-top', U.y + 'px'); root.setProperty('--U-left', U.x + 'px');
    // ENV-02 §1: every bottom-anchored layer offsets by the occluded band.
    root.setProperty('--vv-occ', (state.layout.occ || 0) + 'px');
    var sheetH = 0;
    if (state.layout.mode === 'narrow') {
      var st = layout.sheetTarget(state.sheet.state, state);
      sheetH = state.search.active ? U.h : st.h;
      if (state.sheet.height !== sheetH) state.sheet.height = sheetH;
      root.setProperty('--sheet-h', sheetH + 'px');
      root.setProperty('--col-left-w', '0px'); root.setProperty('--col-detail-w', '0px'); root.setProperty('--topbar-h', '0px');
    } else {
      var c = layout.columns(state);
      state.sheet.height = 0;
      root.setProperty('--sheet-h', '0px');
      root.setProperty('--col-left-w', c.leftW + 'px'); root.setProperty('--col-detail-w', c.detailW + 'px');
      root.setProperty('--topbar-h', c.topbarH + 'px');
      if (state.columns.autoCollapsed !== c.autoCollapsed || state.columns.detailPaused !== c.detailPaused) {
        state.columns.autoCollapsed = c.autoCollapsed; state.columns.detailPaused = c.detailPaused;
      }
    }
    state.layout.mapRect = layout.mapRect(state);
  };

  /** setFabWidth(px) — map publishes its live FAB stack width so pills keep clear. */
  layout.setFabWidth = function (px) { document.documentElement.style.setProperty('--fab-w', Math.round(px) + 'px'); };

  // ENV-02: coalesce resize / visualViewport into one frame; emit settled after quiet window
  var _measureScheduled = false, _settleTimer = null;
  layout.schedule = function () {
    if (_measureScheduled) return;
    _measureScheduled = true;
    util.raf(function () {
      _measureScheduled = false;
      var changed = layout.measure();
      if (changed) { App.requestRender('layout'); }
      clearTimeout(_settleTimer);
      _settleTimer = setTimeout(function () { App.emit('layout:settled', App.state.layout); }, motion.settleMs || 180);
    });
  };
  layout.bind = function () {
    window.addEventListener('resize', layout.schedule);
    window.addEventListener('orientationchange', layout.schedule);
    // The Android shell writes --app-inset-top at first paint and again at READY, both of
    // which can land after the boot measure and neither of which resizes the window. One
    // re-measure at load costs nothing and is what picks that value up. (STANDARDS §1.2a)
    window.addEventListener('load', layout.schedule);
    if (window.visualViewport) {
      window.visualViewport.addEventListener('resize', layout.schedule);
      window.visualViewport.addEventListener('scroll', layout.schedule);
    }
  };

  /* ========================================================================
     nav — one back router (NAV-03): highest visible layer wins, one history
     entry per real layer, Esc + popstate, IME-safe
     ==================================================================== */
  var nav = App.nav = {};
  var MODAL_KINDS = ['bookmarkForm', 'listForm', 'lightbox', 'importDialog'];
  var SECONDARY_KINDS = ['layers', 'more', 'memberPicker', 'share', 'placeMenu', 'account', 'regionPicker', 'sortMenu', 'help'];
  nav.MODAL_KINDS = MODAL_KINDS; nav.SECONDARY_KINDS = SECONDARY_KINDS;
  var _transient = [];          // [{name, close}] pushed by modules (sub-layers inside modals, e.g. emoji picker)
  var _layers = [];             // the layer stack, as of the last sync
  var _entries = 0;             // history entries we have actually pushed
  var _suppress = 0;            // popstate events we caused ourselves
  var _fromPop = false;

  /** nav.push(name, closeFn) — register a transient top layer (closes via closeFn on Back/Esc). */
  nav.push = function (name, closeFn) {
    _transient.push({ name: name, close: closeFn });
    App.requestRender('nav');
  };
  /** nav.pop(name) — remove a transient layer after it closed itself. */
  nav.pop = function (name) {
    for (var i = _transient.length - 1; i >= 0; i--) if (_transient[i].name === name) { _transient.splice(i, 1); break; }
    App.requestRender('nav');
  };

  /** activeLayers(state) → ordered list (bottom → top) of layer names currently visible. */
  nav.activeLayers = function (state) {
    state = state || App.state;
    var L = [];
    // The panel keeps its own history entry UNDER the detail. It used to be
    // excluded while a detail was open, so opening a card from the list left
    // the stack the same length, nothing was pushed, and the Back that closed
    // the card consumed the panel's only entry — the next Back then did
    // nothing at all (and on Android the one after it left the app).
    if (state.layout.mode === 'narrow' && state.sheet.state !== 'collapsed') L.push('browse');
    if (state.selected.id) L.push('detail');
    if (state.multi.active) L.push('multi');
    if (state.search.active) L.push('search');
    if (state.overlay.kind && SECONDARY_KINDS.indexOf(state.overlay.kind) >= 0) L.push('overlay:' + state.overlay.kind);
    if (state.overlay.kind && MODAL_KINDS.indexOf(state.overlay.kind) >= 0) L.push('modal:' + state.overlay.kind);
    _transient.forEach(function (tl) { L.push('transient:' + tl.name); });
    return L;
  };
  nav.top = function (state) { var L = nav.activeLayers(state); return L.length ? L[L.length - 1] : null; };

  /**
   * closeLayer(name) — the single close action per layer. Emits an event
   * first so the owning module can veto/extend, then applies the state.
   */
  nav.closeLayer = function (name, state) {
    state = state || App.state;
    if (name.indexOf('transient:') === 0) {
      var tl = _transient[_transient.length - 1];
      if (tl) { _transient.pop(); try { tl.close(); } catch (e) { console.error(e); } }
      App.requestRender('nav'); return true;
    }
    if (name.indexOf('modal:') === 0 || name.indexOf('overlay:') === 0) {
      var kind = state.overlay.kind;
      App.emit('overlay:close', { kind: kind, payload: state.overlay.payload, reason: 'back' });
      App.set({ overlay: { kind: null, payload: null } });
      App.emit('overlay:closed', { kind: kind });
      return true;
    }
    if (name === 'search') {
      App.emit('search:cancel', { reason: 'back' });
      App.set({ search: { active: false, activeIndex: -1 } });   // query kept (SEARCH-03)
      return true;
    }
    if (name === 'multi') {
      App.emit('multi:cancel', { reason: 'back' });
      App.set({ multi: { active: false, ids: new Set() } });
      return true;
    }
    if (name === 'detail') {
      var origin = state.selected.origin;
      var prev = { id: state.selected.id, origin: origin, anchor: state.selected.anchor };
      App.emit('detail:close', { reason: 'back', selected: prev });
      var patch = { selected: { id: null, origin: null, anchor: null }, columns: { detailOpen: false } };
      if (state.layout.mode === 'narrow') {
        if (origin === 'results' || origin === 'saved' || origin === 'filters') patch.sheet = { state: 'browse', tab: origin === 'filters' ? 'filters' : origin };
        else patch.sheet = { state: 'collapsed' };
      }
      App.set(patch);
      App.emit('nav:restore', prev);      // list / filters restore scroll anchor + focus (NAV-02) after geometry settles
      return true;
    }
    if (name === 'browse') {
      App.emit('sheet:collapse', { reason: 'back' });
      App.set({ sheet: { state: 'collapsed' } });
      return true;
    }
    return false;
  };

  /** nav.back({fromHistory}) → true if a layer was closed, false → hand to the browser. */
  nav.back = function (opts) {
    var topLayer = nav.top(App.state);
    if (!topLayer) return false;
    _fromPop = !!(opts && opts.fromHistory);
    var ok = nav.closeLayer(topLayer, App.state);
    App.flushNow();
    _fromPop = false;
    return ok;
  };

  /**
   * sync(state) — keep exactly one history entry per open layer.
   *
   * This used to compare the CURRENT stack against the PREVIOUS stack, which
   * is wrong whenever a single change both closes one layer and opens another:
   * the two lengths match, nothing is pushed, and the layer that is now open
   * has no entry of its own. Two real cases hit it — a Back that closed a card
   * and re-opened the result panel underneath it, and a wide→narrow rotation
   * that turned a detail column into a detail sheet. Both left a panel the
   * Back button could not close, and on Android the press after that left the
   * app.
   *
   * `_entries` is what the browser actually holds for us, so it is what the
   * arithmetic is done against. A pop has already consumed one before we run.
   */
  nav.sync = function (state) {
    var cur = nav.activeLayers(state);
    if (_fromPop && _entries > 0) _entries -= 1;
    if (cur.length > _entries) {
      for (var i = _entries; i < cur.length; i++) {
        try { history.pushState({ jpfm40: true, depth: i + 1, layer: cur[i] }, ''); _entries += 1; }
        catch (e) { /* file:// or sandbox */ }
      }
    } else if (cur.length < _entries) {
      var n = _entries - cur.length;
      _entries -= n;
      _suppress += n;
      try { history.go(-n); } catch (e) { _suppress -= n; }
      // safety: if the browser never fires popstate (e.g. no entries), clear suppression later
      setTimeout(function () { _suppress = 0; nav.stamp(); }, 400);
    }
    _layers = cur;
    nav.stamp();
  };

  /** stamp() — rewrite the current history entry so it describes the layer
   *  stack as it is NOW. history.go() is asynchronous: a programmatic close
   *  followed quickly by a new open used to leave the entry describing a layer
   *  that had already been dismissed, and the Back that landed on it did
   *  nothing visible. */
  nav.stamp = function () {
    var n = _layers.length;
    try {
      history.replaceState(n ? { jpfm40: true, depth: n, layer: _layers[n - 1] }
                             : { jpfm40: true, depth: 0, base: true }, '');
    } catch (e) { /* file:// or sandbox */ }
  };
  nav.depth = function () { return _layers.length; };

  nav.bind = function () {
    window.addEventListener('popstate', function () {
      if (_suppress > 0) { _suppress -= 1; if (_suppress === 0) nav.stamp(); return; }
      nav.back({ fromHistory: true });
    });
    document.addEventListener('keydown', function (e) {
      if (e.key !== 'Escape') return;
      if (e.isComposing || e.keyCode === 229) return;          // IME owns Esc (I18N-02)
      if (e.defaultPrevented) return;
      if (nav.back()) { e.preventDefault(); }
    }, false);
    _entries = 0;
    try { history.replaceState({ jpfm40: true, depth: 0, base: true }, ''); } catch (e) { /* ignore */ }
  };

  /* ========================================================================
     high-level intents shared by several modules (thin, state-only)
     ==================================================================== */
  var act = App.act = {};

  /** openDetail(id, origin, anchor) — select a restaurant (NAV-01 origin kept on in-detail switches). */
  act.openDetail = function (id, origin, anchor) {
    var s = App.state;
    var keepOrigin = s.selected.id && s.selected.origin && (origin === 'map' || origin === 'candidates' || origin === undefined);
    var patch = {
      userDraggedMap: false,
      selected: { id: id, origin: keepOrigin ? s.selected.origin : (origin || 'map'), anchor: keepOrigin ? s.selected.anchor : (anchor || null) },
      columns: { detailOpen: true },
      detail: { scrollTo: 0 }
    };
    if (s.layout.mode === 'narrow') patch.sheet = { state: 'detail' };
    // INTEGRATION (LAY-02): choosing a restaurant is a request to *see* it. A stale
    // 'open' preference on the left column turned that into detailPaused — the column
    // stayed, the detail never appeared and the click looked dead at Fold-inner width.
    // Clear the preference so the auto-collapse rule decides; a user who reopens the
    // left column afterwards sets it again and gets the documented pause.
    if (s.layout.mode !== 'narrow' && s.columns.userLeftPreference === 'open') {
      patch.columns.userLeftPreference = null;
    }
    if (s.multi.active) return;                 // multi: row body toggles selection instead (LIST-01)
    App.set(patch);
    App.emit('detail:open', { id: id, origin: patch.selected.origin });
    App.emit('map:reveal', { id: id, reason: 'select' });     // LAY-05 one reveal request per explicit select
  };
  /** closeDetail() — explicit ×: narrow → collapsed map, wide → release column (NAV-01). */
  act.closeDetail = function () {
    var s = App.state;
    var prev = { id: s.selected.id, origin: s.selected.origin, anchor: s.selected.anchor };
    App.emit('detail:close', { reason: 'x', selected: prev });
    var patch = { selected: { id: null, origin: null, anchor: null }, columns: { detailOpen: false } };
    if (s.layout.mode === 'narrow') patch.sheet = { state: 'collapsed' };
    App.set(patch);
  };
  act.openOverlay = function (kind, payload) {
    App.emit('overlay:open', { kind: kind, payload: payload });
    // INTEGRATION (overlays coreRequest #1): App.set deep-merges plain objects, so a
    // previous overlay's payload keys would survive into the new one (memberPicker's
    // {id} leaking into listForm turned "create" into "edit"). Null it first.
    if (App.state.overlay.payload) App.set({ overlay: { payload: null } }, { silent: true });
    App.set({ overlay: { kind: kind, payload: payload === undefined ? null : payload } });
  };
  act.closeOverlay = function (reason) {
    var s = App.state; if (!s.overlay.kind) return;
    var kind = s.overlay.kind;
    App.emit('overlay:close', { kind: kind, payload: s.overlay.payload, reason: reason || 'explicit' });
    App.set({ overlay: { kind: null, payload: null } });
    App.emit('overlay:closed', { kind: kind });
  };
  act.setTab = function (tab) {
    var s = App.state;
    var patch = { sheet: { tab: tab } };
    if (s.layout.mode === 'narrow') {
      if (s.selected.id) { /* switching tabs leaves detail → browse */ patch.selected = { id: null, origin: null, anchor: null }; patch.columns = { detailOpen: false }; }
      patch.sheet.state = tab === 'filters' ? 'filter' : 'browse';
    } else {
      patch.columns = { userLeftPreference: 'open' };
    }
    if (s.multi.active) patch.multi = { active: false, ids: new Set() };
    App.set(patch);
    App.emit('tab:changed', tab);
  };
  act.setSheet = function (state, reason) {
    App.set({ sheet: { state: state }, userDraggedMap: false });
    // reason 'drag' means containers will emit sheet:snapped itself once the height
    // transition ends, so we stay quiet here (containers coreRequest #3).
    if (reason !== 'drag') App.emit('sheet:snapped', { state: state, reason: reason || 'explicit' });
  };
  act.toggleFav = function (id) {
    var u = App.state.user;
    var was = u.fav.has(id);
    App.set({ user: { fav: util.setToggle(u.fav, id) } });
    App.emit('user:changed', { kind: 'fav', id: id, added: !was });
    return !was;
  };
  act.setBlack = function (id, on) {
    var u = App.state.user;
    var was = u.black.has(id);
    if (was === !!on) return false;
    App.set({ user: { black: on ? util.setWith(u.black, id) : util.setWithout(u.black, id) } });
    App.emit('user:changed', { kind: 'black', id: id, added: !!on });
    return true;
  };
  /** showToast({kind, text, count, undo, action, remainingMs}) — FEEDBACK-01: one
   *  target; a new undoable replaces the old.
   *  `action` is {label, run} — a labelled recovery button (MAP-03 requires one on
   *  every locate failure, and every Business undo arrives with one). It is part of
   *  the toast shape: do NOT drop it when normalising, or the button disappears. */
  act.showToast = function (toast) {
    var id = util.uid('toast');
    App.set({ toast: { id: id, kind: toast.kind || 'info', text: toast.text, count: toast.count || 0, undo: toast.undo || null, action: toast.action || null, remainingMs: (typeof toast.remainingMs === 'number' ? toast.remainingMs : (motion.toastMs || 9000)), paused: !!toast.paused, startedAt: Date.now() } });
    App.emit('toast:shown', id);
    return id;
  };
  act.dismissToast = function (id) { if (!App.state.toast || (id && App.state.toast.id !== id)) return; App.set({ toast: null }); App.emit('toast:dismissed', id); };
  /** applyFilters(patch) — FILTER-01: apply immediately, no draft. */
  act.applyFilters = function (patch) {
    App.set({ filters: patch });
    App.emit('filters:changed', App.state.filters);
  };
  act.resetFilters = function () {
    var d = App.defaultState().filters;
    App.set({ filters: d, sort: 'rating' });
    App.emit('filters:changed', App.state.filters);
    App.emit('filters:reset');
  };

  /* ========================================================================
     modules
     ==================================================================== */
  /** App.registerModule(name, {init(ctx), render(state, changed), destroy()}) */
  App.registerModule = function (name, mod) {
    App.modules[name] = mod;
    if (App._moduleOrder.indexOf(name) < 0) App._moduleOrder.push(name);
    return mod;
  };
  App.MODULE_ORDER = ['map', 'containers', 'list', 'detail', 'filters', 'overlays'];

  App.ctx = function () {
    return {
      App: App, Data: window.Data, t: t, util: util, icon: App.icon, emoji: emoji, motion: motion, layout: layout, nav: nav, act: act,
      roots: App.roots,
      Business: window.Business, biz: window.Business && window.Business.api,
      leafletMap: App.leafletMap || null, mapEl: App.mapEl || null
    };
  };

  /* ========================================================================
     boot
     ==================================================================== */
  App.params = {};
  function parseParams() {
    var p = {};
    (location.search || '').replace(/^\?/, '').split('&').forEach(function (kv) {
      if (!kv) return; var i = kv.indexOf('=');
      var k = decodeURIComponent(i < 0 ? kv : kv.slice(0, i)), v = i < 0 ? '' : decodeURIComponent(kv.slice(i + 1));
      p[k] = v;
    });
    return p;
  }

  /**
   * App.boot({leafletMap, mapEl, lang}) — called by adapter.js once
   * Business.init has run and folium's map exists. `lang` is the page
   * language Business resolved ('zh'|'tw'|'en'|'ja'); ?lang= and
   * tabelog.lang are Business's to read, never parsed here again.
   */
  App.boot = function (opts) {
    opts = opts || {};
    var p = App.params = parseParams();
    App.leafletMap = opts.leafletMap || null;
    App.mapEl = opts.mapEl || null;
    motion.readTokens();
    App.roots = {};
    ['map-root', 'search-root', 'list-root', 'list-foot', 'detail-root', 'detail-foot', 'filters-root', 'filters-foot',
     'candidates-root', 'toast-root', 'overlay-root', 'modal-root', 'notice-root', 'fab-root'].forEach(function (id) {
      App.roots[id.replace(/-(\w)/g, function (_, c) { return c.toUpperCase(); })] = document.getElementById(id);
    });
    var lang = /^(zh|tw|en|ja)$/.test(opts.lang || '') ? opts.lang : 'zh';
    var fs = [100, 115, 130].indexOf(Number(p.fs)) >= 0 ? Number(p.fs) : 100;
    App.state.lang = lang; App.state.fontScale = fs;
    document.documentElement.lang = util.langLocale(lang);
    document.documentElement.setAttribute('data-fs', String(fs));
    layout.measure();
    var s = App.defaultState();
    s.lang = lang; s.fontScale = fs; s.layout = App.state.layout;
    if (typeof opts.seed === 'function') s = opts.seed(s) || s;   // adapter: prefs + user state
    App.state = s;
    layout.derive(App.state, new Set(['*']));
    // init modules in fixed order
    App.MODULE_ORDER.forEach(function (name) {
      var mod = App.modules[name];
      if (!mod) { console.warn('[boot] module missing: ' + name); return; }
      try { if (typeof mod.init === 'function') mod.init(App.ctx()); } catch (e) { console.error('[init:' + name + ']', e); }
    });
    layout.bind();
    nav.bind();
    _pendingChanged.add('*');
    flushRender();
    layout.schedule();                       // second measure once module CSS is in place; fires layout:settled
    if (App.state.selected.id) App.once('layout:settled', function () { App.emit('map:reveal', { id: App.state.selected.id, reason: 'select' }); });
    App.ready = true;
    App.emit('ready');
  };
})();

/* Photo variants share an identity, but a size is not guaranteed to exist. */
(function () {
  'use strict';
  var good = Object.create(null), sources = Object.create(null);
  function variants(source, size) {
    var u;
    try { u = new URL(source, document.baseURI); } catch (_) { return [source]; }
    if (u.hostname !== 'tblg.k-img.com') return [source];
    var m = u.pathname.match(/\/restaurant\/images\/Rvw\/(\d+)\/(?:\d+x\d+_(?:rect|square)_)?([A-Za-z0-9_-]+)\.jpg$/);
    if (!m) return [source];
    var base = 'https://tblg.k-img.com/restaurant/images/Rvw/' + m[1] + '/';
    return [base + size + 'x' + size + '_rect_' + m[2] + '.jpg',
      base + (size === 320 ? '640x640' : '320x320') + '_rect_' + m[2] + '.jpg',
      source, base + m[2] + '.jpg'].filter(function (x, i, a) { return a.indexOf(x) === i; });
  }
  function key(source) { var a = variants(source, 640); return a[a.length - 1]; }
  function url(source, size) {
    var result = good[key(source)] || variants(source, size || 640)[0];
    sources[result] = source;
    return result;
  }
  function state(img) {
    if (!img._photoAttempt || img._photoAttempt.current !== img.src) {
      img._photoAttempt = { current: img.src, source: sources[img.src] || img.src, tried: [] };
    }
    return img._photoAttempt;
  }
  function isPhoto(img) { return img && img.matches && img.matches('img.dt-photo-img,img.dt-cand-img,img.dt-lb-img,img.ls-img,img.mp-bubble-photo'); }
  document.addEventListener('error', function (e) {
    var img = e.target; if (!isPhoto(img)) return;
    var st = state(img); st.tried.push(img.src);
    var next = variants(st.source, /320x320/.test(st.source) ? 320 : 640).filter(function (u) { return st.tried.indexOf(u) < 0; })[0];
    if (next) { e.stopImmediatePropagation(); st.current = next; img.src = next; }
    else { delete good[key(st.source)]; img.style.visibility = 'hidden'; img.dataset.photoFailed = 'true'; }
  }, true);
  document.addEventListener('load', function (e) {
    var img = e.target; if (!isPhoto(img)) return;
    good[key(img.src)] = img.src; img.style.visibility = ''; delete img.dataset.photoFailed;
  }, true);
  window.PhotoUrls = { variants: variants, url: url };
})();
